[world]
name = "Cartridge Marketplace"
description = "Cartridge Marketplace"
website = "https://github.com/dojoengine/dojo-starter"
seed = "Marketplace-0.0.10"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "MARKETPLACE"

[init_call_args]
"MARKETPLACE-Marketplace" = [
    "0x1",                                                                # Royalties
    "0x0",                                                                # 0% fee
    "0x03F7F4E5a23A712787F0C100f02934c4A88606B7F0C880c2FD43e817E6275d83", # Fee receiver
    "0x041aad5a7493b75f240f418cb5f052d1a68981af21e813ed0a35e96d3e83123b", # Owner
]

[writers]
"MARKETPLACE" = ["MARKETPLACE-Marketplace"]

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"
account_address = "0x041aad5a7493b75f240f418cb5f052d1a68981af21e813ed0a35e96d3e83123b"
keystore_path = "keystore.json"
world_address = "0x0299109d4b17f83ea113efd6f8db76b3c5d644c403670c7ca7ed930047273af2"
world_block = 2012297
ipfs_config.url = "https://ipfs.infura.io:5001"
ipfs_config.username = "2EBrzr7ZASQZKH32sl2xWauXPSA"
ipfs_config.password = "12290b883db9138a8ae3363b6739d220"
