packages:
  - client
  - packages/*
  - contracts
  - worker/*
catalog:
  "@cartridge/ui": github:cartridge-gg/ui#460751b
  "@cartridge/controller": 0.7.13
  "@cartridge/connector": 0.7.13
  "@starknet-react/core": 3.7.4
  "@starknet-react/chains": 3.1.3
  "@dojoengine/core": 1.5.17
  "@dojoengine/sdk": 1.5.18
  "@dojoengine/torii-client": 1.5.16
  "@dojoengine/torii-wasm": 1.5.16
  class-variance-authority: ^0.7.1
  starknet: 6.23.1
  tsup: 8.4.0
  typescript: "5.8"
