packages:
  - "client"
  - "packages/*"
  - "contracts"

catalog:
  "@cartridge/ui": "github:cartridge-gg/ui#3fa3547"
  "@dojoengine/core": 1.5.5
  "@dojoengine/sdk": 1.5.5
  "@dojoengine/torii-client": 1.5.5
  "@dojoengine/torii-wasm": 1.5.5
  starknet: 6.23.1
  tsup: 8.4.0
  typescript: "5.8"
