packages:
  - client
  - packages/*
  - contracts
  - worker/*
catalog:
  "@cartridge/ui": github:cartridge-gg/ui#460751b
  "@cartridge/arcade": 0.0.0
  "@cartridge/controller": 0.7.13
  "@cartridge/connector": 0.7.13
  "@starknet-react/core": 3.7.4
  "@starknet-react/chains": 3.1.3
  "@dojoengine/core": 1.6.0-beta.3
  "@dojoengine/sdk": 1.6.0-beta.3
  "@dojoengine/torii-client": 1.6.0-beta.3
  "@dojoengine/torii-wasm": 1.6.0-beta.3
  class-variance-authority: ^0.7.1
  starknet: 7.6.2
  tsup: 8.4.0
  typescript: "5.8"
