[workspace]
members = ["packages/orderbook", "contracts"]
description = "Dojo marketplace library"
homepage = "https://github.com/cartridge-gg/marketplace"
cairo-version = "2.12.0"

[workspace.package]
version = "0.0.6"
edition = "2024_07"

[workspace.dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", rev = "2d82d6efb28558e726df7eac7b16a4a95999a52c" }
dojo_macros = { git = "https://github.com/dojoengine/dojo", rev = "2d82d6efb28558e726df7eac7b16a4a95999a52c" }
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", rev = "2d82d6efb28558e726df7eac7b16a4a95999a52c" }
openzeppelin_account = "1.0.0"
openzeppelin_token = "1.0.0"
openzeppelin_introspection = "1.0.0"
starknet = "2.12.0"
cairo_test = "2.12.0"

[workspace.tool.fmt]
sort-module-level-items = true

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["dojo::world::world_contract::world"]

[profile.mainnet]
