rpc = "https://api.cartridge.gg/x/starknet/mainnet"
world_address = "0x54f7f579d72c4c48fa99396ea88fdcef0a6569d8c1eda754a6d740a506a204b"

[indexing]
pending = true
polling_interval = 500
max_concurrent_tasks = 100
world_block = 2012297
contracts = []
namespace = ["MARKETPLACE"]
transactions = true

[sql]
historical = []
