[package]
cairo-version = "2.12.0"
edition.workspace = true
name = "marketplace"
version.workspace = true

[cairo]
sierra-replace-ids = true

[scripts]
dev = "sozo clean && sozo build --typescript && sozo migrate plan && sozo migrate apply"

[dependencies]
openzeppelin_introspection.workspace = true
openzeppelin_token.workspace = true
dojo.workspace = true
dojo_macros.workspace = true
orderbook = { path = ".." }
starknet.workspace = true

[dev-dependencies]
openzeppelin_account.workspace = true
dojo_cairo_test.workspace = true
cairo_test.workspace = true

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "orderbook::models::index::m_Access",
    "orderbook::models::index::m_Book",
    "orderbook::models::index::m_Order",
    "orderbook::models::index::m_MetadataAttribute",
    "orderbook::events::index::e_Listing",
    "orderbook::events::index::e_Offer",
    "orderbook::events::index::e_Sale",
]

[profile.mainnet]
